#!/bin/bash
function check_script {
	local scriptpath="$plugindir/ec2-autohostname"
	if [ ! -e $scriptpath ]; then
		die "$scriptpath does not exist!" \
		    "copy '$scriptpath.template' to '$scriptpath' and edit it."
	fi
	
}

check_script

insert_task_after $TASK_PACKAGES \
	$plugindir/tasks/add-dependencies
insert_task_after $TASK_APT_UPGRADE \
	$plugindir/tasks/install-boto
insert_task_before $TASK_INITSCRIPTS \
	$plugindir/tasks/add-init-script
insert_task_after $TASK_INITSCRIPTS \
	$plugindir/tasks/chmod-script
